export const Users = [
  {
    id:1,
    profilePicture: "https://cdn.wallpapersafari.com/68/16/4n6y5c.jpg",
    username: "Lalith Kumar",
  },
  {
    id:2,
    profilePicture: "https://img.freepik.com/free-vector/abstract-swami-vivekananda-element-beige-orange-watercolor-background-illustration-high-resolution-free-photo_1340-22185.jpg?w=2000",
    username: "Dinesh Varma",
  },
  {
    id:3,
    profilePicture: "https://1.bp.blogspot.com/-NZvmmzhLkKc/XJyJ933WedI/AAAAAAAAEr4/PU1r0oEMYxAO4i-YOa8xCINx8ntVG3PiwCLcBGAs/s1600/shri%2Bram.jpg",
    username: "Gopi Sir",
  },
  {
    id:4,
    profilePicture: "https://www.pixelstalk.net/wp-content/uploads/images6/Black-Panther-Wallpaper-HD-Free-download.jpg",
    username: "Hari kiran sir",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Movie updates",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "karthik",
  },
  {
    id:7,
    profilePicture: "https://www.pixelstalk.net/wp-content/uploads/images6/Black-Panther-Wallpaper-HD-Free-download.jpg",
    username: "abhiram",
  },
  {
    id:8,
    profilePicture: "https://img.freepik.com/free-vector/abstract-swami-vivekananda-element-beige-orange-watercolor-background-illustration-high-resolution-free-photo_1340-22185.jpg?w=2000",
    username: "spiderman",
  },
  {
    id:9,
    profilePicture: "https://static01.nyt.com/images/2023/03/29/multimedia/29musk-ai1-bjhm/29musk-ai1-bjhm-superJumbo.jpg",
    username: "ironman",
  },
  {
    id:10,
    profilePicture: "https://vijaykarnataka.com/thumb/99209697/pawan-kalyan-99209697.jpg?imgsize=66050&width=540&height=405&resizemode=75",
    username: "hulk",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "jai hanuman.",
    photo: "assets/post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://c4.wallpaperflare.com/wallpaper/535/901/196/the-avengers-avengers-endgame-avengers-endgame-iron-man-marvel-comics-hd-wallpaper-preview.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://cdn.wallpapersafari.com/68/16/4n6y5c.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://images6.alphacoders.com/102/thumb-1920-1020775.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://www.pixel4k.com/wp-content/uploads/2018/12/captain-marvel-movie-2019-carol-danvers-4k-wallpaper_1544829313.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://www.pixelstalk.net/wp-content/uploads/images6/Black-Panther-Wallpaper-HD-Free-download.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjo2mX5hRMZZH1GxE278S3Zxl2q7FoGllPQPQSp4dexYj2TkrkEV-hk82tAVl_p0wO4KQAFbkg-AzfOufF4_x5AjtYi-DEucx8gPGShyVzu6cOFQ_iQ6ZUluaR4RB-kFjiGNnVQaN7JnJ9SVj5U_sn1dYasFJBhqgdKs1MxRsTUAPZo8bTzIGoGUR_F_A/s0/HDgallery%20Dasara%20Sankranti.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://wallpaperaccess.com/full/1821077.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://images8.alphacoders.com/546/thumb-1920-546442.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://e0.pxfuel.com/wallpapers/382/344/desktop-wallpaper-web-development-front-end.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
